### ISSUE TITLE
Not really an issue, but how to get javascript version of this React component

### ISSUE THREAD

**Issue by iramtay** [kessejones/react-sweetalert2#11]
Hi,

It is not an issue but i am wondering if there is a way to get the javascript version instead since we are not using babel during runtime.

It will be good if someone can help share the process for the runtime in with .tsx or .ts.

Regards.

**Comment by kessejones** [comment]
Hello,

what you need is a library to run directly in the browser, right?

**Comment by iramtay** [comment]
Hi,
Thanks for your reply.
I am new to ReactJS, so i am wondering what is the easiest way to get a library that is able to use without typescript or babel.
If it is an invalid question, please help to guide me along if you can.

Sent from Galaxy Fold 3 
 
  On Sun, 13 Mar 2022 at 1:02, Kesse ***@***.***> wrote:   


Hello,

what you need is a library to run directly in the browser, right?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kessejones** [comment]
Can you add the file https://github.com/kessejones/react-sweetalert2/blob/iife/dist/react-sweetalert2.js in your project and check if it works correctly?


The SweetAlert2 component can be accessed like this: `ReactSweetAlert2.SweetAlert2`

e.g.
```js
React.createElement(ReactSweetAlert2.SweetAlert2, {
  show: true,
  title: "hello"
});

```

**Comment by iramtay** [comment]
Hi,
I tried to include this react-sweetalert2.js into my page.
There is an error where Swal cannot be found.

Regards.

Chee Chong 

    On Monday, March 14, 2022, 06:57:14 AM GMT+8, Kesse Jones ***@***.***> wrote:  
 
 


Can you add the file https://github.com/kessejones/react-sweetalert2/blob/iife/dist/react-sweetalert2.js in your project and check if it works correctly?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kessejones** [comment]
This error happens because react-sweetalert2 depends on sweetalert2. To solve this just add sweetalert2 to your page, and remember to add it before importing react-sweetalert2.

sweetalert2:
```html
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.4.4/dist/sweetalert2.all.min.js"></script>
```

**Comment by iramtay** [comment]
Thanks, the error is not longer there after the include.
Is there a guide on how to do the trigger to show a basic alert? Some help will be good.
Regards.
Chee Chong 

    On Monday, March 14, 2022, 09:33:18 AM GMT+8, Kesse Jones ***@***.***> wrote:  
 
 


This error happens because react-sweetalert2 depends on sweetalert2. To solve this just add sweetalert2 to your page, and remember to add it before importing react-sweetalert2.

sweetalert2:
<script ***@***.***/dist/sweetalert2.all.min.js"></script>
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kessejones** [comment]
You can use the README examples but as you are only using javascript you will have to create the components through the React.createElement function.

Using JSX:
```tsx
export default function App(){
    const [swalProps, setSwalProps] = useState({});
    return (
        <div>
            <button onClick={() => {
                setSwalProps({
                    show: true,
                    title: 'Basic Usage',
                    text: 'Hello World',
                });
            }}>
                Open
            </button>

            <SweetAlert2 {...swalProps} />
        </div>
    );
}
```

Using React.createElement
```js
function App() {
    const [swalProps, setSwalProps] = useState({});
    return React.createElement(
        'div',
        null,
        React.createElement(
            'button',
            { onClick: () => {
                    setSwalProps({
                        show: true,
                        title: 'Basic Usage',
                        text: 'Hello World'
                    });
                } },
            'Open'
        ),
        React.createElement(ReactSweetAlert2.SweetAlert2, swalProps)
    );
}
```

**Comment by iramtay** [comment]
Hi, 
Thanks for the code, i can see the alert showing.
Somehow, it will not appear for the second time. Do i need to clear the state or something?
Regards.
Chee Chong 

    On Tuesday, March 15, 2022, 08:01:10 AM GMT+8, Kesse Jones ***@***.***> wrote:  
 
 


You can use the README examples but as you are only using javascript you will have to create the components through the React.createElement function.

Using JSX:
export default function App(){
    const [swalProps, setSwalProps] = useState({});
    return (
        <div>
            <button onClick={() => {
                setSwalProps({
                    show: true,
                    title: 'Basic Usage',
                    text: 'Hello World',
                });
            }}>
                Open
            </button>

            <SweetAlert2 {...swalProps} />
        </div>
    );
}
Using React.createElement
function App() {
    const [swalProps, setSwalProps] = useState({});
    return React.createElement(
        'div',
        null,
        React.createElement(
            'button',
            { onClick: () => {
                    setSwalProps({
                        show: true,
                        title: 'Basic Usage',
                        text: 'Hello World'
                    });
                } },
            'Open'
        ),
        React.createElement(ReactSweetAlert2.SweetAlert2, swalProps)
    );
}
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by iramtay** [comment]
Sorry, one more question.
Why if we need to trigger the alert programmatically? It is not from click but due to other validations to show the alert.It seems like it will work for the first time, and will not go into useEffect() the second time onwards.
Regards.
Chee Chong 

    On Tuesday, March 15, 2022, 09:06:27 AM GMT+8, Tay Chee Chong ***@***.***> wrote:  
 
 Hi, 
Thanks for the code, i can see the alert showing.
Somehow, it will not appear for the second time. Do i need to clear the state or something?
Regards.
Chee Chong 

    On Tuesday, March 15, 2022, 08:01:10 AM GMT+8, Kesse Jones ***@***.***> wrote:  
 
 


You can use the README examples but as you are only using javascript you will have to create the components through the React.createElement function.

Using JSX:
export default function App(){
    const [swalProps, setSwalProps] = useState({});
    return (
        <div>
            <button onClick={() => {
                setSwalProps({
                    show: true,
                    title: 'Basic Usage',
                    text: 'Hello World',
                });
            }}>
                Open
            </button>

            <SweetAlert2 {...swalProps} />
        </div>
    );
}
Using React.createElement
function App() {
    const [swalProps, setSwalProps] = useState({});
    return React.createElement(
        'div',
        null,
        React.createElement(
            'button',
            { onClick: () => {
                    setSwalProps({
                        show: true,
                        title: 'Basic Usage',
                        text: 'Hello World'
                    });
                } },
            'Open'
        ),
        React.createElement(ReactSweetAlert2.SweetAlert2, swalProps)
    );
}
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kessejones** [comment]
SweetAlert2 has an event called didClose, and in it you can update the show state to false, so whenever the alert closes its state will be updated.

**Comment by iramtay** [comment]
Thanks for the great help.
I am able to get it running with a React component. However in order to clear the show state to false, i have to call ReactDOM.render or it will not work. Is it correct as what you indicate or is there a more effective way?

 trigger() { this.state.swalProps = { show: true, icon: 'success', didClose: () => { this.state.swalProps = { show: false }  //is it correct to do the render to clear the state? ReactDOM.render( React.createElement(ReactSweetAlert2.SweetAlert2, this.state.swalProps),  document.getElementById(this.state.layer) ); } }; ReactDOM.render( React.createElement(ReactSweetAlert2.SweetAlert2, this.state.swalProps),  document.getElementById(this.state.layer) ); }

Regards.
Chee Chong 

    On Tuesday, March 15, 2022, 09:20:55 PM GMT+8, Kesse Jones ***@***.***> wrote:  
 
 


SweetAlert2 has an event called didClose, and in it you can update the show state to false, so whenever the alert closes its state will be updated.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kessejones** [comment]
It is not necessary to call ReactDOM.render.
You just need to manage the state and ensure that when you close the alert the show property is updated to false.
