### ISSUE TITLE
The "Confirm", "Cancel" buttons are disabled after an Error occurring

### ISSUE THREAD

**Issue by vladwwe24** [kessejones/react-sweetalert2#13]
When error occured in preConfirm, all buttons are disabled. How to make them enabled again?
![image](https://user-images.githubusercontent.com/33057400/159796065-ba59218a-7c02-45ad-b508-db223821d182.png)

Code:
<SweetAlert2
            {...swalProps}
            preConfirm={() => {
                if (inputRef.current.value) {
                    return alertServices.setAppointment(appointment.id, inputRef.current.value)
                        .then(response => {
                            console.log(response.status);
                            if (response.status !== 403) return response;
                            throw new Error("API works incorrect");
                        });
                }
                throw new Error("Empty field data cannot be sent");
            }}
            onError={error => {
                setErrorMessage(error.message);
            }}
            onConfirm={() => {
                props.setUpdateTable(true);
            }}
            didClose={() => {
                setAppointment('');
                props.setApptAlert({...props.apptAlert, displayAlert: false});
            }}
        >
            h1 className="mb-4">Appointment Info</h1
            {errorMessage && <Alert variant="filled" severity="error" className="mb-2">{errorMessage}</Alert>}
            <LocalizationProvider dateAdapter={AdapterDateFns}>
                <MobileDateTimePicker
                    value={appointment.appointment}
                    inputRef={inputRef}
                    label="Date/Time"
                    onChange={newValue => setAppointment({...appointment, appointment: newValue})}
                    renderInput={(params) => <TextField {...params} />}
                />
            </LocalizationProvider>
        </SweetAlert2>

**Comment by kessejones** [comment]
At the moment we don't have a way to enable the buttons through properties, but in your case, you could call your `setErrorMessage` directly in the `preConfirm` and then return false to prevent the popup from closing, so it would not be necessary to deal with errors with `onError`.

I'm planning on mapping the action functions like `Swal.enableButtons() ` to attributes of the `SweetAlert2` component, so it will be possible to handle all these cases by state.

thank you for reporting.
