### ISSUE TITLE
Not able to install as npm package

### ISSUE THREAD

**Issue by sagarvaish2823** [kessejones/react-sweetalert2#18]
This is the error while npm install

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: trrinket-client@0.1.0    
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"18.2.0" from the root project    
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.2" from react-sweetalert2@0.5.2
npm ERR! node_modules/react-sweetalert2
npm ERR!   react-sweetalert2@"*" from the root project    
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry   
npm ERR! this command with --force or --legacy-peer-deps  
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by xtianbar** [comment]
try this npm i react-sweetalert2@0.5.1

**Comment by obah** [comment]
npm i react-sweetalert2@0.5.1 still gives the same error

**Comment by kessejones** [comment]
Are you using any framework like remix or next.js ?

**Comment by obah** [comment]
Yes, next.js. And I was able to get it to work using npm i react-sweetalert2 --legacy-peer-deps

**Comment by kessejones** [comment]
I published a new version, let me know if you still have an error
