### ISSUE TITLE
Cannot flush updates when React is already rendering warnings in console

### ISSUE THREAD

**Issue by oliemansm** [kessejones/react-sweetalert2#7]
When using this library I'm getting the warning in the console stated in the subject. After trying a couple of things I've been able to get rid of it by using `useEffect` instead of calling `run()` directly as you're doing here. I'm no longer using your lib, but this still might be of interest to you in case you want to apply the same kind of fix for your library.

```javascript
const SweetAlert = ({
  show, onConfirm, onError, ...rest
}) => {
  useEffect(() => {
    if (show) {
      mySwal.fire(rest)
        .then(result => onConfirm && onConfirm(result))
        .catch(error => onError && onError(error))
    }
  }, [show, onConfirm, onError, rest])

  return null
}
```

**Comment by kessejones** [comment]
Thanks for the recommendation. I will release a fix version by applying this.
