### ISSUE TITLE
SweetAlert2: Unknown parameter "children"

### ISSUE THREAD

**Issue by aykutkardas** [kessejones/react-sweetalert2#8]
I can't use children in SweetAlert. I want to show some of my special elements in SweetAlert.

Sample
```jsx
<SweetAlert {...swal}>
 <input type="text" onChange={this.handleChange} />
</SweetAlert>
```

**Comment by kessejones** [comment]
The SweetAlert component can not to have children. It encapsulates attributes to pass to swal and within the context of swal it is not possible to render with JSX only with HTML using the `html` attribute

**Comment by aykutkardas** [comment]
It can actually be integrated.

https://github.com/sweetalert2/sweetalert2-react-content

**Comment by kessejones** [comment]
Interesting, I didn't know that was possible. I will work on something along those lines.
